### ISSUE TITLE
Various crossmod compatibility issues

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#76]
This tickets track various mod having incompatibilities with WarpDrive:
- [x] Artifacts antibuilder block (ship can bypass its area, block can be moved with a ship)
- [x] ItemPhysics disabling WarpDrive space gravity
- [x] ArsMagica2: mana network
- [x] OpenModularTurrets: cloak not working
- [x] GalacticCraft: gravity disabled in space
- [ ] Advanced Nuclear control: card using absolute coordinates
- [ ] Advanced Nuclear control: information panels facing
- [ ] RF Tools support

Unconfirmed compatibility:
- [x] ArsMagica2: multiblocks
- [x] GregTech5: multiblocks

**Comment by LemADEC** [comment]
GT block orientation works fine, multiblocks aren't tested yet.
ArsMagica2 power nodes are saved in unusual places, hence it's not working.

**Comment by LemADEC** [comment]
As per map content, ArsMagica2 structures don't need special treatment.

**Comment by LemADEC** [comment]
As per map content, GregTech structures don't need special treatment.

**Comment by LemADEC** [comment]
ArsMagica2 network isn't accessible => won't fix

**Comment by LemADEC** [comment]
ArsMagica2 network is fixed in c2eeeee58589df85a5fd6c28e0d83ec3962249d7

**Comment by CaptainMegavolt** [comment]
Problem with Mekanism and warpdrive. Whenever I warp or cloak, all of my Universal Cables and Energy Cubes disappear, but the game still thinks there is a glitch block there. Only way to get rid of them=WorldEdit. Is is possible to fix this so that Mekanism cables and pipes work on ships? (1.6.4 and 1.7.10 versions)

**Comment by LemADEC** [comment]
1.6.4 works with Mekanism, I've fixed it in my branch, we were using it on my WorldWarMinecraft season 6 public server for a year.
1.7.10 wasn't tested with Mekanism.

**Comment by CaptainMegavolt** [comment]
Oh. I was probably using Anon1644's 1.6.4 version.

**Comment by LemADEC** [comment]
For RF Tools, refer to #84 McJty/RFTools#318

**Comment by LemADEC** [comment]
Artifacts anti-builder is actually fixed since we do plugin support.

**Comment by ghost** [comment]
I have OMT and i seem to have no cloaking problems at all. Only the turrets can still see the entitys but not hit for some reason

**Comment by ghost** [comment]
And i suggest taking a look at reika's mods like rotarycraft because i think they cause forcefield problems. And take a look if chromaticraft doesnt fuckup in space dimension

**Comment by LemADEC** [comment]
OMT is already fixed, hence the tick mark next to that line in the list.
What force field issue exists with RotaryCraft?

**Comment by ghost** [comment]
The problem with the forcefields that dont respond. I think that is caused by rotarycraft or reactorcraft. I tested it without them and forcefields worked again. Im going to test with them and see if they cause trouble

**Comment by LemADEC** [comment]
RF Tools was done during the 1.12.2 port.
Advanced Nuclear control is no longer maintained => out.
